### ISSUE TITLE
Notion-enhancer not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by noel-schneider** [notion-enhancer/desktop#663]
**describe the bug**
I tried to install notion-enhancer following the README.md:
```
bash curl -sL https://deb.nodesource.com setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs
npm i -g notion-enhancer
```

However, after running:
`sudo notion-enhancer apply`

I got these logs:
```
=== NOTION ENHANCEMENT LOG ===
(node:5971) UnhandledPromiseRejectionWarning: EnhancerError: nothing found: platform not supported.
    at getNotionResources (/usr/local/lib/node_modules/notion-enhancer/pkg/helpers.js:86:11)
    at module.exports (/usr/local/lib/node_modules/notion-enhancer/pkg/apply.js:25:20)
    at CAC.cli.command.action (/usr/local/lib/node_modules/notion-enhancer/bin.js:30:36)
    at CAC.runMatchedCommand (/usr/local/lib/node_modules/notion-enhancer/node_modules/cac/dist/index.js:614:34)
    at CAC.parse (/usr/local/lib/node_modules/notion-enhancer/node_modules/cac/dist/index.js:541:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/notion-enhancer/bin.js:71:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
(node:5971) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5971) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And when I run:
`sudo notion-enhancer check`

It says:
`nothing found: platform not supported.`

**platform**
Ubuntu 20.04

**Comment by dragonwocky** [comment]
@noel-schneider the notion-enhancer isn't an app by itself. To install it that way, you need to have the Notion app pre-existing/installed/working on your computer - which you can't do on Ubuntu, since there is no official Notion app for Ubuntu.

You can install notion-enhancer & Notion together as a .deb from https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-5
