### ISSUE TITLE
notion-enhancer not working on ubuntu 21.10

### ISSUE THREAD

**Issue by yessGlory17** [notion-enhancer/desktop#733]
notion-enhancer apply -d
[NOTION-ENHANCER] APPLY
Error:  notion installation has been corrupted, no executable found.
  at default (file:///usr/local/lib/node_modules/notion-enhancer/pkg/apply.mjs:27:13)
  at file:///usr/local/lib/node_modules/notion-enhancer/bin.mjs:105:25
  at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
  at async loadESM (node:internal/process/esm_loader:88:5)
  at async handleMainPromise (node:internal/modules/run_main:61:12)

**Comment by dragonwocky** [comment]
you can't install the notion-enhancer like that on linux - manual enhancement requires a vanilla/official build of the Notion app installed from the https://www.notion.so/desktop website (which you can't have on linux).

try reading the installation instructions, they include a section about installing on ubuntu: https://notion-enhancer.github.io/getting-started/installation
