### ISSUE TITLE
Notion JavaScript error in main process (MacOS)

### ISSUE THREAD

**Issue by Alejandro-16bit** [notion-enhancer/desktop#740]
Hello,
I recently came across an error after running the command `npm i -g notion-enhancer ` that was prompted on the notion desktop application. Before this, I noticed that the notion enhancer was missing the color-scheme on the home window and I assumed the command was to fix this bug.

I am prompted with the following after launching the notion desktop application. I could not find any forum with a solution, any help is greatly appreciated.

_current version: notion-enhancer/0.11.0 darwin-x64/21.4.0 node/v16.8.0_

Error prompt:

Uncaught Exception:
Error: Cannot find module '/usr/local/lib/node_modules/notion-enhancer/pkg/loader.js'
Require stack:
- /Applications/Notion.app/Contents/Resources/app/config.js
- /Applications/Notion.app/Contents/Resources/app/main/crashReporter.js
- /Applications/Notion.app/Contents/Resources/app/main/main.js
- 
at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
at Module._load (internal/modules/cjs/loader.js:848:27)
at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/Applications/Notion.app/Contents/Resources/app/config.js:8:1)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
at Module.load (internal/modules/cjs/loader.js:992:32)

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/desktop/issues/684, use notion-repackaged instead for now
